apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: skaffold-debug-go
    context: go
  - image: skaffold-debug-python
    context: python
  - image: skaffold-debug-netcore
    context: netcore
  - image: skaffold-debug-nodejs
    context: nodejs
  # ensure images are tagged with :latest
  tagPolicy:
    sha256: {}
test:
  - image: skaffold-debug-go
    structureTests: [./test/structure-tests-go.yaml]
  - image: skaffold-debug-python
    structureTests: [./test/structure-tests-python.yaml]
  - image: skaffold-debug-netcore
    structureTests: [./test/structure-tests-netcore.yaml]
  - image: skaffold-debug-nodejs
    structureTests: [./test/structure-tests-nodejs.yaml]
deploy:
  kubectl:
    manifests: []

profiles:
  # local: builds to local daemon only
  - name: local
    build:
      local:
        push: false

  # Set of `skaffold debug`-like integration tests
  - name: integration
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: go113app
          context: integration/goapp
          docker:
            buildArgs:
              GOVERSION: 1.13
      - op: add
        path: /build/artifacts/-
        value:
          image: go114app
          context: integration/goapp
          docker:
            buildArgs:
              GOVERSION: 1.14
      - op: add
        path: /build/artifacts/-
        value:
          image: go115app
          context: integration/goapp
          docker:
            buildArgs:
              GOVERSION: 1.15
      - op: add
        path: /build/artifacts/-
        value:
          image: nodejs12app
          context: integration/nodejsapp
          docker:
            buildArgs:
              NODEVERSION: 12.16.0
    deploy:
      kubectl:
        manifests:
          - integration/k8s-*.yaml

  # prod: pushes images to production with :latest
  - name: prod
    build:
      local:
        push: true

  # Use short (deprecated) image names: images were renamed so they were
  # more easily distinguished from other images with similar names.
  - name: deprecated-names
    patches:
      - op: replace
        path: /build/artifacts/0/image
        from: skaffold-debug-go
        value: go
      - op: replace
        path: /test/0/image
        from: skaffold-debug-go
        value: go

      - op: replace
        path: /build/artifacts/1/image
        from: skaffold-debug-python
        value: python
      - op: replace
        path: /test/1/image
        from: skaffold-debug-python
        value: python

      - op: replace
        path: /build/artifacts/2/image
        from: skaffold-debug-netcore
        value: netcore
      - op: replace
        path: /test/2/image
        from: skaffold-debug-netcore
        value: netcore

      - op: replace
        path: /build/artifacts/3/image
        from: skaffold-debug-nodejs
        value: nodejs
      - op: replace
        path: /test/3/image
        from: skaffold-debug-nodejs
        value: nodejs

