apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: gcr.io/gcp-dev-tools/duct-tape/go
    context: go
  - image: gcr.io/gcp-dev-tools/duct-tape/python
    context: python
  - image: gcr.io/gcp-dev-tools/duct-tape/netcore
    context: netcore
test:
  - image: gcr.io/gcp-dev-tools/duct-tape/go
    structureTests: [./test/structure-tests-go.yaml]
  - image: gcr.io/gcp-dev-tools/duct-tape/python
    structureTests: [./test/structure-tests-python.yaml]
  - image: gcr.io/gcp-dev-tools/duct-tape/netcore
    structureTests: [./test/structure-tests-netcore.yaml]
deploy:
  kubectl:
    manifests:
      - test/k8s-test-installation.yaml

profiles:
  # pushes images to production with :latest
  - name: prod
    build:
      tagPolicy:
        envTemplate:
          template: '{{.IMAGE_NAME}}:latest'
