apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: container-debug-support

.YamlAnchors:
  _integration: &integration
    activeProfiles:
     - name: integration
       activatedBy: [integration]

requires:
- path: go
  <<: *integration
- path: netcore
  <<: *integration
- path: nodejs
  <<: *integration
- path: python
  <<: *integration

profiles:
- name: integration
