apiVersion: skaffold/v1beta9
kind: Config
build:
  artifacts:
  - image: gcr.io/gcp-dev-tools/duct-tape/go
    context: go
  - image: gcr.io/gcp-dev-tools/duct-tape/python
    context: python
  - image: gcr.io/gcp-dev-tools/duct-tape/netcore
    context: netcore
  - image: gcr.io/gcp-dev-tools/duct-tape/nodejs
    context: nodejs
test:
  - image: gcr.io/gcp-dev-tools/duct-tape/go
    structureTests: [./test/structure-tests-go.yaml]
  - image: gcr.io/gcp-dev-tools/duct-tape/python
    structureTests: [./test/structure-tests-python.yaml]
  - image: gcr.io/gcp-dev-tools/duct-tape/netcore
    structureTests: [./test/structure-tests-netcore.yaml]
  - image: gcr.io/gcp-dev-tools/duct-tape/nodejs
    structureTests: [./test/structure-tests-nodejs.yaml]
deploy:
  kubectl:
    manifests: []

profiles:
  # local: builds to local daemon only
  - name: local
    build:
      local:
        push: false

  # Set of `skaffold debug`-like integration tests
  - name: integration
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: go113app
          context: integration/goapp
          docker:
            buildArgs:
              GOVERSION: 1.13
      - op: add
        path: /build/artifacts/-
        value:
          image: go114app
          context: integration/goapp
          docker:
            buildArgs:
              GOVERSION: 1.14
      - op: add
        path: /build/artifacts/-
        value:
          image: nodejs12app
          context: integration/nodejsapp
          docker:
            buildArgs:
              NODEVERSION: 12.16.0
    deploy:
      kubectl:
        manifests:
          - integration/k8s-*.yaml

  # prod: pushes images to production with :latest
  - name: prod
    build:
      local:
        push: true
      tagPolicy:
        envTemplate:
          template: '{{.IMAGE_NAME}}:latest'
