apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: python

requires:
- path: ../integration
  activeProfiles:
   - name: integration
     activatedBy: [integration]

build:
  local:
    useBuildkit: true
  artifacts:
  - image: skaffold-debug-python
    context: helper-image
    custom:
      buildCommand: ../../buildx.sh
  # ensure images are tagged with :latest
  tagPolicy:
    sha256: {}

test:
  - image: skaffold-debug-python
    structureTests: [structure-tests.yaml]

deploy:
  logs:
    prefix: auto
  kubectl:
    manifests: []

profiles:
  # local: builds to local daemon only
  - name: local
    build:
      local:
        push: false

  # Set of `skaffold debug`-like integration tests
  - name: integration
    patches:
      - op: add
        path: /build/artifacts/-
        value:
          image: python39app
          context: test/pythonapp
          docker:
            buildArgs:
              PYTHONVERSION: 3.9
      - op: add
        path: /build/artifacts/-
        value:
          image: pydevconnect
          context: test/pydevconnect

    deploy:
      kubectl:
        manifests:
          - test/k8s-test-python39.yaml

  # prod: pushes images to production with :latest
  - name: prod
    build:
      local:
        push: true

  # Use short (deprecated) image names: images were renamed so they were
  # more easily distinguished from other images with similar names.
  - name: deprecated-names
    patches:
      - op: replace
        path: /build/artifacts/0/image
        from: skaffold-debug-python
        value: python
      - op: replace
        path: /test/0/image
        from: skaffold-debug-python
        value: python
