apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
  - image: gcr.io/gcp-dev-tools/duct-tape
    context: duct-tape

  # simple image that lists the contents of / and /dbg
  - image: test-image
    context: test/test-image
test:
  - image: gcr.io/gcp-dev-tools/duct-tape
    structureTests:
      - ./test/duct-tape-structure-tests.yaml
deploy:
  kubectl:
    manifests:
      - test/k8s-test-installation.yaml
