apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
  - image: gcr.io/gcp-dev-tools/duct-tape
    context: duct-tape
test:
  - image: gcr.io/gcp-dev-tools/duct-tape
    structureTests:
      - ./test/*
deploy:
  kubectl:
    manifests:
      - k8s-*
