apiVersion: v1
kind: Pod
metadata:
  name: go115pod
spec:
  containers:
  - name: go115app
    image: go115app
    args:
    - /dbg/go/bin/dlv
    - exec
    - --log
    - --headless
    - --continue
    - --accept-multiclient
    - --listen=localhost:56286
    - --api-version=2
    - ./app
    ports:
    - containerPort: 8080
    - containerPort: 56286
      name: dlv
    readinessProbe:
      httpGet:
        path: /
        port: 8080
    volumeMounts:
    - mountPath: /dbg
      name: go-debugging-support
  initContainers:
  - image: gcr.io/gcp-dev-tools/duct-tape/go
    name: install-go-support
    resources: {}
    volumeMounts:
    - mountPath: /dbg
      name: go-debugging-support
  volumes:
  - emptyDir: {}
    name: go-debugging-support

---
apiVersion: batch/v1
kind: Job
metadata:
  name: connect-to-go115
  labels:
    project: container-debug-support
    type: integration-test
spec:
  ttlSecondsAfterFinished: 10
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: kubectl
        emptyDir: {}
      initContainers:
      - name: copy-kubectl
        image: bitnami/kubectl
        command: [sh, -c, 'cp -p /opt/bitnami/kubectl/bin/kubectl /kubectl/kubectl']
        volumeMounts:
        - mountPath: /kubectl
          name: kubectl
      containers:
      - name: dlv-to-go115
        image: gcr.io/gcp-dev-tools/duct-tape/go
        command: [sh, -c, 'sleep 5;
          /kubectl/kubectl port-forward pod/go115pod 56286:56286 &
          sleep 2;
          (echo bt; echo exit -c) > init.txt;
          set -x;
          /duct-tape/go/bin/dlv connect --init init.txt localhost:56286']
        volumeMounts:
        - mountPath: /kubectl
          name: kubectl


