apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: integration

deploy:
  logs:
    prefix: auto
  kubectl:
    manifests: []

profiles:
  # local: never push to remote registries
  - name: local
    build:
      local:
        push: false

  # integration: set of `skaffold debug`-like integration tests
  - name: integration
    build:
      artifacts:
      - image: kubectl
        context: kubectl
        custom:
          buildCommand: ../../dockerbuild.sh --build-arg=GOVERSION=1.16
    deploy:
      kubectl:
        manifests:
          - k8s-rbac.yaml

