apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: integration

deploy:
  logs:
    prefix: auto
  kubectl:
    manifests: []

profiles:
  # integration: set of `skaffold debug`-like integration tests
  - name: integration
    build:
      artifacts:
      - image: kubectl
        context: kubectl
        custom:
          buildCommand: docker buildx build --build-arg=GOVERSION=1.16
            $(if [ "${PUSH_IMAGES}" = true ]; then echo --push; else echo --load; fi)
            --tag $IMAGE "$BUILD_CONTEXT"
    deploy:
      kubectl:
        manifests:
          - k8s-rbac.yaml

